### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jakemcivor** [nelsonii/JoystickEnclosures#1]
You've mentioned the intention to release these designs open-source, which is awesome. If that is the case, you should choose an appropriate license and list it to be explicit about what you'd like people to be able to do or not do. 

The Open-Source Hardware Association has some good guidance: https://www.oshwa.org/sharing-best-practices

**Comment by nelsonii** [comment]
I've updated repositories to either fall under "MIT License" or "The Unlicense".
